version: '3'

vars:
  IMAGE_NAME: ifs-cloud-mcp-server
  IMAGE_TAG: '{{default "latest" .IMAGE_TAG}}'
  VERSION: '{{default "25.1.0" .VERSION}}'
  REGISTRY: '{{default "" .REGISTRY}}'

tasks:
  # Development tasks
  install:
    desc: Install dependencies for development
    cmds:
      - pip install -e ".[dev]"
    
  install-uv:
    desc: Install dependencies using uv package manager
    cmds:
      - uv sync --dev
  
  format:
    desc: Format code using black
    cmds:
      - python -m black src/ tests/
  
  lint:
    desc: Lint code using ruff
    cmds:
      - python -m ruff check src/ tests/
  
  type-check:
    desc: Run type checking with mypy
    cmds:
      - python -m mypy src/
  
  test:
    desc: Run tests
    cmds:
      - python -m pytest tests/ -v
  
  test-coverage:
    desc: Run tests with coverage
    cmds:
      - python -m pytest tests/ --cov=src --cov-report=html --cov-report=term
  
  # Docker tasks
  docker-build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} .
  
  docker-run:
    desc: Run Docker container
    cmds:
      - docker run -it --rm -p 8000:8000 -e VERSION={{.VERSION}} {{.IMAGE_NAME}}:{{.IMAGE_TAG}}
  
  docker-run-stdio:
    desc: Run Docker container in stdio mode (for testing)
    cmds:
      - docker run -it --rm {{.IMAGE_NAME}}:{{.IMAGE_TAG}} server --version {{.VERSION}} --transport stdio
  
  docker-shell:
    desc: Open shell in Docker container
    cmds:
      - docker run -it --rm {{.IMAGE_NAME}}:{{.IMAGE_TAG}} /bin/bash
  
  docker-push:
    desc: Push Docker image to registry
    preconditions:
      - test -n "{{.REGISTRY}}"
    cmds:
      - docker tag {{.IMAGE_NAME}}:{{.IMAGE_TAG}} {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}
      - docker push {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}
  
  docker-clean:
    desc: Remove Docker images and containers
    cmds:
      - docker rm $(docker ps -a -q -f ancestor={{.IMAGE_NAME}}) 2>/dev/null || true
      - docker rmi {{.IMAGE_NAME}}:{{.IMAGE_TAG}} 2>/dev/null || true
  
  # Local server tasks
  server:
    desc: Start MCP server in stdio mode
    cmds:
      - python -m ifs_cloud_mcp_server.main server --version {{.VERSION}}
  
  server-http:
    desc: Start MCP server in HTTP mode
    cmds:
      - python -m ifs_cloud_mcp_server.main server --version {{.VERSION}} --transport streamable-http --port 8000
  
  server-sse:
    desc: Start MCP server in SSE mode
    cmds:
      - python -m ifs_cloud_mcp_server.main server --version {{.VERSION}} --transport sse --port 8000
  
  # CI/CD tasks
  ci:
    desc: Run all CI checks
    cmds:
      - task: format
      - task: lint
      - task: type-check
      - task: test
  
  build-all:
    desc: Build and test everything
    cmds:
      - task: ci
      - task: docker-build
  
  # Help
  default:
    desc: Show available tasks
    cmds:
      - task --list
